<?php
  require_once 'php/header.php';

  if(isset($_POST["email"]) && isset($_POST["password"])) {
    $email = cleanSQL($_POST["email"]);
    $password = cleanSQL($_POST["password"]);
    $result = request("SELECT forename FROM users WHERE email='$email' AND password='$password'");
    if($result->num_rows == 0) {
      $login = "Email eller password er forkert";
      $loggedin = FALSE;
    } else {
      $row = $result->fetch_assoc();
      $_SESSION["user"] = $row["forename"];
      $loggedin = TRUE;
      header("Location: index.php");
    }
  }
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>rambuk.net</title>
  <link rel="stylesheet" type="text/css" href="stylesheets/style.css">
</head>
<body>
  <div class="grid-container">
    <div class="left-clear"></div>
    <div class="right-clear"></div>
    <div class="header bgcolor-0 color-1">
      <h1>Rambuk.net</h1>
    </div>
    <div class="navbar">
      <div class="bgcolor-2 color-4"><a class="active" href="#">Hjem</a></div>
      <div class="bgcolor-2 color-4"><a href="#">Matematik</a></div>
      <div class="bgcolor-2 color-4"><a href="#">Science</a></div>
      <div class="bgcolor-2 color-4"><a href="#">Fysik/Kemi</a></div>
      <div class="bgcolor-2 color-4"><a href="bootstrap.php">Andet</a></div>
    </div>
    <div class="main container">
      <h3>Nostrum sed, illum nihil deserunt totam fuga voluptatem, atque veritatis.</h3>
      <h4>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat adipisci doloremque dolorem quidem esse fuga corrupti quam itaque, dolores voluptatibus blanditiis nobis ipsa, repudiandae deserunt vitae optio a quis mollitia!</h4>
      <p>#####  Color Palette by Paletton.com <br>
         *** Primary color:<br>
         shade 0 = #7B9F35 = rgb(123,159, 53) = rgba(123,159, 53,1) = rgb0(0.482,0.624,0.208)<br>
         shade 1 = #3F5E00 = rgb( 63, 94,  0) = rgba( 63, 94,  0,1) = rgb0(0.247,0.369,0)<br>
         shade 2 = #577E09 = rgb( 87,126,  9) = rgba( 87,126,  9,1) = rgb0(0.341,0.494,0.035)<br>
         shade 3 = #A5BF71 = rgb(165,191,113) = rgba(165,191,113,1) = rgb0(0.647,0.749,0.443)<br>
         shade 4 = #D4DFBE = rgb(212,223,190) = rgba(212,223,190,1) = rgb0(0.831,0.875,0.745)<br>
         #####  Generated by Paletton.com (c) 2002-2014.</p>
    </div>
    <div class="right-menu container">
      <?php
      if(!$loggedin) {
        echo <<<_END
        <h4>Login <br><span style="visibility: hidden;">-</span><span style="color: red;">$login</span></h4>
        <form action="index.php" method="post">
          <input style="opacity: 0;position: absolute;"> <!-- fake form, to avoid google autoinput -->
          <input type="password" style="opacity: 0;position: absolute;">
          <div class="login-form">
            <label>Email</label>
            <input type="email" class="login-input" placeholder="Indtast email" name="email" required="required">
          </div>
          <div class="login-form">
            <label>Password</label>
            <input type="password" class="login-input" placeholder="Password" name="password" required="required">
          </div>
          <button type="submit" class="login-button">Login</button>
          <button style="margin-left: 12px;" type="button" class="login-button" onclick="window.location.href='signup.php'">Registrer</button>
        </form>
_END;
      } else {
          echo <<<_END
          <h4>Velkommen $user</h4>
          <button class="login-button" onclick="window.location.href='logout.php'">Logout</button>
_END;
      } ?>

    </div>
    <div class="footer grid-footer container bgcolor-1">
      <div class="footer-item f-link1 container"></div>
      <div class="footer-item f-link2 container"></div>
      <div class="footer-item f-link3 container"></div>
      <div class="footer-item f-link4 container"></div>
      <div class="footer-item f-link5 container"></div>
    </div>
  </div>
</body>
</html>
